---
title: 自定义异常类
header-includes:
 - \usepackage{fvextra}
 - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
output:
  pdf_document:
    latex_engine: xelatex
    toc: true
    template: C:/Huaxv/Huaxv-Tool/markdown-preview=enhanced/template.tex
    highlight: tango
    path: C:/Users/huaxv/Desktop/自定义异常类.pdf
---

# 自定义异常类

自定义异常类：继承一个异常类，实现一个默认构造器，实现一个参数是字符串的构造器，该参数可以用于错误说明，超类会用作 `toString` 方法的返回值

如下示例：

```java
import java.util.*;
import java.io.*;

class AException extends Exception {
    AException() {}
    AException(String info) { super(info); }
}

class BException extends Exception {
    BException() {}
    BException(String info) { super(info); }
}

public class Main {
    void solve() throws AException, BException {
        var rd = new Random(new Date().getTime());
        if (rd.nextBoolean()) throw new AException("A 类型错误");
        else throw new BException("B 类型错误");
    }
    public static void main(String[] args) {
        var cmd = new Main();
        try {
            cmd.solve();
        }
        catch (Exception e) {
            System.out.println(e);
        }
    }
}
```

---

如果一个方法可能会放回多种错误对象，必须得用 `throws` 提前一一说明，用逗号隔开：

```java
void solve() throws AException, BException {
    var rd = new Random(new Date().getTime());
    if (rd.nextBoolean()) throw new AException("A 类型错误");
    else throw new BException("B 类型错误");
}
```

抛出异常用关键字 `throw` 抛出一个『异常类对象』即可

---

捕获异常：

```java
try {} // 尝试运行，如果发生异常，执行 catch 语句块的内容
catch (Exception e) {}
```

```java
try {} // 尝试运行，如果发生异常，按异常发生的类型执行 catch 语句块的内容
catch (AException e) {}
catch (BException e) {}
```

错误例子：

```java
try {} // 如果捕获到异常，因为 Exception 是其他两个类的超类，导致一个异常可以被两个语句块同时捕获而报错
catch (Exception e) {}
catch (AException e) {}
catch (BException e) {}
```

示例：

```java
import java.util.*;
import java.io.*;

class AException extends Exception {
    AException() {}
    AException(String info) { super(info); }
}

class BException extends Exception {
    BException() {}
    BException(String info) { super(info); }

}

public class Main {
    void solve() throws AException, BException {
        var rd = new Random(new Date().getTime());
        if (rd.nextBoolean()) throw new AException("A 类型错误");
        else throw new BException("B 类型错误");
    }
    public static void main(String[] args) {
        var cmd = new Main();
        try {
            cmd.solve();
        }
        catch (AException e) {
            System.out.println(e);
        }
        catch (BException e) {
            System.out.println(e);
        }
    }
}
```

也可以合并捕获异常，即如果遇到了多个异常，但是处理方案却一样，可能在同一个 `catch` 块中捕获：

```java
try {}
catch (AException | BException e) {}
```

示例：

```java
import java.util.*;
import java.io.*;

class AException extends Exception {
    AException() {}
    AException(String info) { super(info); }
}

class BException extends Exception {
    BException() {}
    BException(String info) { super(info); }

}

public class Main {
    void solve() throws AException, BException {
        var rd = new Random(new Date().getTime());
        if (rd.nextBoolean()) throw new AException("A 类型错误");
        else throw new BException("B 类型错误");
    }
    public static void main(String[] args) {
        var cmd = new Main();
        try {
            cmd.solve();
        }
        catch (AException | BException e) {
            System.out.println(e);
        }
    }
}
```

---

无论是否被捕获到异常，都会执行 `finally` 语句块的内容

如果没有捕获到异常，执行 `finally` 语句块，如果捕获到了异常，先执行 `catch` 语句块，然后继续执行 `finally` 语句块：



```java
try {}
catch (Exception e) {}
finally {}
```

`final` 语句是一定会执行的，不管你是否 `return` 或者 `throw`

```java
import java.util.*;
import java.io.*;

public class Main {
    int solve() {
        try {
            System.out.println("return 之前");
            return 0;
        }
        finally {
            System.out.println("return 过后");
            return 1;
        }
    }
    public static void main(String[] args) {
        var cmd = new Main();
        System.out.println(cmd.solve());
    }
}
```

输出：

甚至，try 里面的 `return` 语句被 finally 的 `return` 语句覆盖掉了

```java
return 之前
return 过后
1
```
